import fs from 'node:fs';
const key=process.env.OPENROUTER_API_KEY,out=process.env.BENCH_OUTPUT;if(!key||!out||fs.existsSync(out))throw Error('key and fresh output required');
const models=['deepseek/deepseek-v4.1-flash','qwen/qwen3.8-flash','qwen/qwen3.7-flash','inclusionai/ling-3.0-flash','openai/gpt-oss-120b','openai/gpt-oss-20b','inception/mercury-2.5','amazon/nova-micro-v1','cohere/command-r7b-12-2024','microsoft/phi-4','mistralai/mistral-nemo','google/gemma-4-26b-a4b-it:free','nvidia/nemotron-3.5-lightning:free','poolside/laguna-xs-2.1:free'];
const cases=JSON.parse(fs.readFileSync('docs/benchmark-results/paired-v1/cases.json','utf8'));
const catalog=await (await fetch('https://openrouter.ai/api/v1/models')).json();
for(const model of models){const m=catalog.data.find(m=>m.id===model);if(!m||+m.pricing.prompt<0||+m.pricing.completion<0||+m.pricing.prompt>.00000015||+m.pricing.completion>.0000006)throw Error('price gate '+model);}
fs.writeFileSync(out+'.manifest.json',JSON.stringify({models,cases,max_tokens:2048,timeout:90000,concurrency:4,noRetries:true,priceCap:{prompt:.15,completion:.6},catalog:catalog.data.filter(m=>models.includes(m.id))},null,2));
const jobs=models.flatMap(model=>cases.map(c=>({model,c})));let index=0;
async function worker(){while(index<jobs.length){const {model,c}=jobs[index++];const start=Date.now();let row;
try{const r=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},signal:AbortSignal.timeout(90000),body:JSON.stringify({model,messages:[{role:'user',content:c.prompt}],max_tokens:2048,provider:{allow_fallbacks:false,max_price:{prompt:.15,completion:.6}}})});const d=await r.json();const text=d.choices?.[0]?.message?.content??'';let value=text.trim();if(typeof c.expected!=='string'){try{value=JSON.parse(text);}catch{}}row={id:c.id,family:c.family,model,status:r.status,pass:r.ok&&JSON.stringify(value)===JSON.stringify(c.expected),text,usage:d.usage,finish:d.choices?.[0]?.finish_reason,error:d.error?.code};}catch(e){row={id:c.id,family:c.family,model,pass:false,error:e.name};}row.ms=Date.now()-start;fs.appendFileSync(out,JSON.stringify(row)+'\n');console.log(model,c.id,row.pass,row.status??row.error);}}
await Promise.all(Array.from({length:4},worker));
